### ISSUE TITLE
Debug with Qt 4.8.6+QtCreator 3.3.81+Cmake 2.8.12.2 faild

### ISSUE THREAD

**Issue by dottob** [jeanyves-yang/cloth_simulation#1]
I am a new c++ start, i like your source,but,see the title *^_^*
So,Would you like tell me your softwares's version?
Thank you very much!
Have a nice day!

**Comment by dottob** [comment]
Ok,use Ubuntu,work fine!nice work!Thank share!

No need qtcreator,just cmake+opengl+qt under Ubuntu 14.02

/*-----------------------------------------------------------------*/
1.download:

a.http://download.qt.io/archive/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.tar.gz
b.http://download.qt.io/development_releases/qtcreator/3.6/3.6.0-rc1/qt-creator-opensource-linux-x86_64-3.6.0-rc1.run

2.install cmake

sudo apt-get install build-essential
wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
tar xf cmake-3.4.1.tar.gz
cd cmake-3.4.1
sudo ./configure
make
sudo apt-get install checkinstall
sudo checkinstall
sudo make install
cmake --version

3.install g++,c++,codeblocks

sudo apt-get install build-essential
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install codeblocks

4.install opengl

sudo apt-get install mesa-common-dev
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libglu1-mesa-dev
sudo apt-get install freeglut3-dev
sudo apt-get install libglew-dev
sudo apt-get install build-essential gdb subversion
sudo apt-get install automake autoconf libtool
sudo apt-get install libgtk2.0-dev
sudo apt-get install libxmu-dev
sudo apt-get install libxxf86vm-dev

5.install qt4.8.6:unpack qt-everywhere-opensource-src-4.8.6.tar.gz somewhere and rename folder "qt4.8.6"

sudo apt-get install libfontconfig1-dev libfreetype6-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxrandr-dev libxrender-dev
cd qt4.8.6
sudo ./configure
make -j8
sudo make install
PATH=/usr/local/Trolltech/Qt-4.8.6/bin:$PATH  
export PATH

6.install qtcreator 
sudo ./qt-creator-opensource-linux-x86_64-3.6.0-rc1.run

the end

![ubuntu 001](https://user-images.githubusercontent.com/5080189/27039488-ac67e8dc-4fc0-11e7-9919-1e8a9d8936b4.JPG)
![ubuntu 002](https://user-images.githubusercontent.com/5080189/27039490-ac6b088c-4fc0-11e7-8b14-4ed3bcb68347.JPG)
![ubuntu 003](https://user-images.githubusercontent.com/5080189/27039489-ac69c602-4fc0-11e7-8d62-2b443082e365.JPG)

**Comment by jeanyves-yang** [comment]
Sorry for the late reply, and thanks for the feedback, I guess I should write up a proper readme or update the CMakeLists to check for versions. But since it was a really small project I didn't bother at that time.

**Comment by dottob** [comment]
to Jeanyves-yang:
You are so modest:)
It's my mistake as a beginner:)
Your projects is fine,the readme is clear to follow.
Initial i can't get it work,because i test them under window system.So i can't get: execinfo.h,-ldl,-lglew and noway to make them work.(Maybe them can work under windows,just i didn't know how to).
And Thanks for your share again:)
To me it's a big:)
Have a nice day!
